### ISSUE TITLE
TestMimeReadWrite#testCreateMailInMailDb hits ClassCastException when using the Notes JVM

### ISSUE THREAD

**Issue by jesse-gallagher** [HCL-TECH-SOFTWARE/domino-jnx#6]
This is presumably from picking up a provider that's present in the Notes JVM jvm/lib/ext directory.

```
java.lang.ClassCastException: com.sun.mail.handlers.text_plain incompatible with jakarta.activation.DataContentHandler
	at jakarta.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601)
	at jakarta.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:554)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289)
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
	at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
	at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
	at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2238)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2198)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1877)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1854)
	at com.hcl.domino.jna.test.TestMimeReadWrite.lambda$0(TestMimeReadWrite.java:97)
```

This was observed in Notes 11.0.0 on macOS, but not on 11.0.1, so it may be a moot point. Still worth keeping an eye on for the short term, though.

**Comment by jesse-gallagher** [comment]
This is a different situation nowadays with Notes 14 and above, so it's been obviated by time.
